site_name: 图像/视频算法
site_description: 图像/视频相关算法以及引申的工具和生活内容
site_author: wjizhong
site_url: https://wjizhong.github.io

repo_name: 'wjizhong'
repo_url: https://github.com/wjizhong

theme:
    name: null
    custom_dir: custom
    # Copy settings from mkdocs_theme.yml, which is ignored by custom_dir themes.
    static_templates: [404.html]
    search_index_only: true
    include_search_page: true

# This should be renamed to nav for mkdocs 1.0+
nav:
    - 个人简历: index.md
    - 工程内容:
        - 计算机概论: 工程内容/计算机概论.md
        - linux三剑客: 工程内容/linux三剑客.md
    - 比赛内容:
        - leetcode:
            - 题目0001:两数之和: 比赛内容/leetcode/题目0001_两数之和.md
            - 题目0002:两数相加: 比赛内容/leetcode/题目0002_两数相加.md
            - 题目0005:最长回文子串: 比赛内容/leetcode/题目0005_最长回文子串.md
            - 题目0010:正则表达式匹配: 比赛内容/leetcode/题目0010_正则表达式匹配.md
            - 题目0019:删除链表的倒数第N个节点: 比赛内容/leetcode/题目0019_删除链表的倒数第N个节点.md
            - 题目0020:有效的括号: 比赛内容/leetcode/题目0020_有效的括号.md
            - 题目0051:N皇后: 比赛内容/leetcode/题目0051_N皇后.md
            - 题目0053:最大子序和: 比赛内容/leetcode/题目0053_最大子序和.md
            - 题目0070:爬楼梯: 比赛内容/leetcode/题目0070_爬楼梯.md
            - 题目0072:编辑距离: 比赛内容/leetcode/题目0072_编辑距离.md
            - 题目0120:三角形最小路径和: 比赛内容/leetcode/题目0120_三角形最小路径和.md
            - 题目0260:只出现一次的数字III: 比赛内容/leetcode/题目0260_只出现一次的数字III.md
            - 题目0300:最长上升子序列: 比赛内容/leetcode/题目0300_最长上升子序列.md
            - 题目0319:灯泡开关: 比赛内容/leetcode/题目0319_灯泡开关.md
            - 题目0382:链表随机节点: 比赛内容/leetcode/题目0382_链表随机节点.md
            - 题目0398:随机数索引: 比赛内容/leetcode/题目0398_随机数索引.md
            - 题目1143:最长公共子序列: 比赛内容/leetcode/题目1143_最长公共子序列.md
            - 题目1318:或运算的最小翻转次数: 比赛内容/leetcode/题目1318_或运算的最小翻转次数.md
    - 其他内容:
        - Emoji表情: 其他内容/Emoji表情.md
        - unicode字符: 其他内容/unicode字符.md
        - 推箱子: 其他内容/推箱子.html
        - 国际象棋: 其他内容/国际象棋.html
        - 五子棋: 其他内容/五子棋.html
markdown_extensions:
    - toc:
        permalink: true
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_png
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde

extra:
    history_buttons: false
