site_name: 图像/视频算法
site_description: 图像/视频相关算法以及引申的工具和生活内容
site_author: wjizhong
site_url: https://wjizhong.github.io

repo_name: 'wjizhong'
repo_url: https://github.com/wjizhong

theme:
    name: null
    custom_dir: custom
    # Copy settings from mkdocs_theme.yml, which is ignored by custom_dir themes.
    static_templates: [404.html]
    search_index_only: true
    include_search_page: true

# This should be renamed to nav for mkdocs 1.0+
nav:
    - 个人简历: index.md
    - 工程内容:
        - 计算机概论: 工程内容/计算机概论.md
        - linux三剑客: 工程内容/linux三剑客.md
        - DOCKER教程: 工程内容/DOCKER教程.md
        - shell教程: 工程内容/shell教程.md
        - 前端教程: 工程内容/前端教程.md
        - c/c++教程:
            - c/c++基础教程: 工程内容/c_c++教程/c_c++基础教程.md
        - python教程:
            - python基础: 工程内容/python教程/python基础.md
            - python模块: 工程内容/python教程/python模块.md
    - 算法内容:
        - 算法基础: 算法内容/算法基础.md
        - 最近邻: 算法内容/最近邻.md
        - 聚类: 算法内容/聚类.md
        - 分解成分信号: 算法内容/分解成分信号.md
        - QR内容: 算法内容/QR算法.md
        - 数据结构: 算法内容/数据结构.md
        - 特征学习: 算法内容/特征学习.md
        - 集成方法: 算法内容/集成方法.md
    - 图像知识:
        - 音频知识: 图像算法/音频知识.md
        - 图像算法: 图像算法/图像算法.md
    - 深度学习:
        - 深度学习基础: 深度学习/深度学习基础.md
        - 深度500问:
            - 第05章_卷积神经网络(CNN): 深度学习/深度500问/第05章_卷积神经网络(CNN).md
            - 第07章_生成对抗网络(GAN): 深度学习/深度500问/第07章_生成对抗网络(GAN).md
            - 第08章_目标检测: 深度学习/深度500问/第08章_目标检测.md
    - 项目内容:
        - makefile教程: 项目内容/makefile教程.md
        - faiss项目: 项目内容/faiss项目.md
        - caffe项目: 项目内容/caffe项目.md
    - 比赛内容:
        - Leetcode:
            - 题目0001:两数之和: 比赛内容/leetcode/题目0001:两数之和
            - 题目0002:两数相加: 比赛内容/leetcode/题目0002:两数相加
            - 题目0004:寻找两个正序数组的中位数: 比赛内容/leetcode/题目0004:寻找两个正序数组的中位数
            - 题目0005:最长回文子串: 比赛内容/leetcode/题目0005:最长回文子串
            - 题目0010:正则表达式匹配: 比赛内容/leetcode/题目0010:正则表达式匹配
            - 题目0019:删除链表的倒数第N个节点: 比赛内容/leetcode/题目0019:删除链表的倒数第N个节点
            - 题目0020:有效的括号: 比赛内容/leetcode/题目0020:有效的括号
            - 题目0023:合并K个排序链表: 比赛内容/leetcode/题目0023:合并K个排序链表
            - 题目0028:实现strStr(): 比赛内容/leetcode/题目0028:实现strStr()
            - 题目0030:串联所有单词的子串: 比赛内容/leetcode/题目0030:串联所有单词的子串
            - 题目0032:最长有效括号: 比赛内容/leetcode/题目0032:最长有效括号
            - 题目0039:组合总和: 比赛内容/leetcode/题目0039:组合总和
            - 题目0042:接雨水: 比赛内容/leetcode/题目0042:接雨水
            - 题目0044:通配符匹配: 比赛内容/leetcode/题目0044:通配符匹配
            - 题目0046:全排列: 比赛内容/leetcode/题目0046:全排列
            - 题目0048:旋转图像: 比赛内容/leetcode/题目0048:旋转图像
            - 题目0051:N皇后: 比赛内容/leetcode/题目0051:N皇后
            - 题目0053:最大子序和: 比赛内容/leetcode/题目0053:最大子序和
            - 题目0056:合并区间: 比赛内容/leetcode/题目0056:合并区间
            - 题目0058:最后一个单词的长度: 比赛内容/leetcode/题目0058:最后一个单词的长度
            - 题目0064:最小路径和: 比赛内容/leetcode/题目0064:最小路径和
            - 题目0070:爬楼梯: 比赛内容/leetcode/题目0070:爬楼梯
            - 题目0072:编辑距离: 比赛内容/leetcode/题目0072:编辑距离
            - 题目0076:最小覆盖子串: 比赛内容/leetcode/题目0076:最小覆盖子串
            - 题目0085:最大矩形: 比赛内容/leetcode/题目0085:最大矩形
            - 题目0099:恢复二叉搜索树: 比赛内容/leetcode/题目0099:恢复二叉搜索树
            - 题目0100:相同的树: 比赛内容/leetcode/题目0100:相同的树
            - 题目0105:从前序与中序遍历序列构造二叉树: 比赛内容/leetcode/题目0105:从前序与中序遍历序列构造二叉树
            - 题目0120:三角形最小路径和: 比赛内容/leetcode/题目0120:三角形最小路径和
            - 题目0124:二叉树中的最大路径和: 比赛内容/leetcode/题目0124:二叉树中的最大路径和
            - 题目0136:只出现一次的数字: 比赛内容/leetcode/题目0136:只出现一次的数字
            - 题目0141-0142:环形链表: 比赛内容/leetcode/题目0141-0142:环形链表
            - 题目0155:最小栈: 比赛内容/leetcode/题目0155:最小栈
            - 题目0208:实现Trie(前缀树): 比赛内容/leetcode/题目0208:实现Trie(前缀树)
            - 题目0215:数组中的第K个最大元素: 比赛内容/leetcode/题目0215:数组中的第K个最大元素
            - 题目0236:二叉树的最近公共祖先: 比赛内容/leetcode/题目0236:二叉树的最近公共祖先
            - 题目0238:除自身以外数组的乘积: 比赛内容/leetcode/题目0238:除自身以外数组的乘积
            - 题目0260:只出现一次的数字III: 比赛内容/leetcode/题目0260:只出现一次的数字III
            - 题目0279:完全平方数: 比赛内容/leetcode/题目0279:完全平方数
            - 题目0287:寻找重复数: 比赛内容/leetcode/题目0287:寻找重复数
            - 题目0297:二叉树的序列化与反序列化: 比赛内容/leetcode/题目0297:二叉树的序列化与反序列化
            - 题目0300:最长上升子序列: 比赛内容/leetcode/题目0300:最长上升子序列
            - 题目0312:戳气球: 比赛内容/leetcode/题目0312:戳气球
            - 题目0319:灯泡开关: 比赛内容/leetcode/题目0319:灯泡开关
            - 题目0347:前K个高频元素: 比赛内容/leetcode/题目0347:前K个高频元素
            - 题目0382:链表随机节点: 比赛内容/leetcode/题目0382:链表随机节点
            - 题目0398:随机数索引: 比赛内容/leetcode/题目0398:随机数索引
            - 题目0461:汉明距离: 比赛内容/leetcode/题目0461:汉明距离
            - 题目0543:二叉树的直径: 比赛内容/leetcode/题目0543:二叉树的直径
            - 题目0617:合并二叉树: 比赛内容/leetcode/题目0617:合并二叉树
            - 题目0647:回文子串: 比赛内容/leetcode/题目0647:回文子串
            - 题目0796:旋转字符串: 比赛内容/leetcode/题目0796:旋转字符串
            - 题目1143:最长公共子序列: 比赛内容/leetcode/题目1143:最长公共子序列
            - 题目1318:或运算的最小翻转次数: 比赛内容/leetcode/题目1318:或运算的最小翻转次数
        - Hiho比赛:
            - Hiho第001周:最长回文子串: 比赛内容/Hiho比赛/Hiho第001周_最长回文子串.md
            - Hiho第002周:Trie树:  比赛内容/Hiho比赛/Hiho第002周_Trie树.md
            - Hiho第003周:KMP算法: 比赛内容/Hiho比赛/Hiho第003周_KMP算法.md
            - Hiho第004周:Trie图: 比赛内容/Hiho比赛/Hiho第004周_Trie图.md
            - Hiho第005周_数字三角形: 比赛内容/Hiho比赛/Hiho第005周_数字三角形.md
            - Hiho第006周:01背包: 比赛内容/Hiho比赛/Hiho第006周_01背包.md
            - Hiho第007周:完全背包: 比赛内容/Hiho比赛/Hiho第007周_完全背包.md
            - Hiho第008周:状态压缩·一: 比赛内容/Hiho比赛/Hiho第008周_状态压缩·一.md
            - Hiho第010周:后序遍历: 比赛内容/Hiho比赛/Hiho第010周_后序遍历.md
            - Hiho第011周:树中的最长路: 比赛内容/Hiho比赛/Hiho第011周_树中的最长路.md
            - Hiho第012周:刷油漆: 比赛内容/Hiho比赛/Hiho第012周_刷油漆.md
            - Hiho第013周:最近公共祖先·一: 比赛内容/Hiho比赛/Hiho第013周_最近公共祖先·一.md
            - Hiho第014周:无间道之并查集: 比赛内容/Hiho比赛/Hiho第014周_无间道之并查集.md
            - Hiho第015周:最近公共祖先·二: 比赛内容/Hiho比赛/Hiho第015周_最近公共祖先·二.md
            - Hiho第016周:RMQ-ST算法: 比赛内容/Hiho比赛/Hiho第016周_RMQ-ST算法.md
            - Hiho第092周:数论一·Miller-Rabin质数测试.md: 比赛内容/Hiho比赛/Hiho第092周_数论一·Miller-Rabin质数测试.md
            - Hiho第093周:数论二·Eular质数筛法: 比赛内容/Hiho比赛/Hiho第093周_数论二·Eular质数筛法.md
            - Hiho第094周:数论三·约瑟夫问题: 比赛内容/Hiho比赛/Hiho第094周_数论三·约瑟夫问题.md
            - Hiho第095周:数论四·扩展欧几里德: 比赛内容/Hiho比赛/Hiho第095周_数论四·扩展欧几里德.md
            - Hiho第096周:数论五·欧拉函数: 比赛内容/Hiho比赛/Hiho第096周_数论五·欧拉函数.md
            - Hiho第097周:数论六·模线性方程组: 比赛内容/Hiho比赛/Hiho第097周_数论六·模线性方程组.md
            - Hiho第098周:搜索一·24点: 比赛内容/Hiho比赛/Hiho第098周_搜索一·24点.md
            - Hiho第099周:搜索二·骑士问题: 比赛内容/Hiho比赛/Hiho第099周_搜索二·骑士问题.md
            - Hiho第100周:搜索三·启发式搜索: 比赛内容/Hiho比赛/Hiho第100周_搜索三·启发式搜索.md            
            - Hiho第101周:搜索四·跳舞链: 比赛内容/Hiho比赛/Hiho第101周_搜索四·跳舞链.md
            - Hiho第102周:搜索五·数独: 比赛内容/Hiho比赛/Hiho第102周_搜索五·数独.md
            - Hiho第190周:震荡数组: 比赛内容/Hiho比赛/Hiho第190周_震荡数组.md
            - Hiho第301周:缺失的拼图: 比赛内容/Hiho比赛/Hiho第301周_缺失的拼图.md
            - 编程练习赛070: 比赛内容/Hiho比赛/编程练习赛70.md
            - 编程练习赛089: 比赛内容/Hiho比赛/编程练习赛89.md
        - 剑指Offer:
            - 求1+2+…+n: 比赛内容/剑指Offer/求1+2+…+n.md
            - 顺时针打印矩阵: 比赛内容/剑指Offer/顺时针打印矩阵.md
            - 最小的k个数: 比赛内容/剑指Offer/最小的k个数.md
            - 表示数值的字符串:  比赛内容/剑指Offer/表示数值的字符串.md
    - 数学内容:
        - 概率与数据统计: 数学内容/概率与数据统计.md
        - 正态分布前世今生: 数学内容/正态分布前世今生.md
        - 数学曲线: 数学内容/数学曲线.md
        - 摆线知识: 数学内容/摆线知识.md
        - 开普勒定律: 数学内容/开普勒定律.md
    - 其他内容:
        - 数学代数: 其他内容/数学代数.md
        - 概率统计: 其他内容/概率统计.md
        - 摄影教程: 其他内容/摄影教程.md
        - Emoji表情: 其他内容/Emoji表情.md
        - unicode字符: 其他内容/unicode字符.md
        - 推箱子: 其他内容/推箱子.html
        - 国际象棋: 其他内容/国际象棋.html
        - 五子棋: 其他内容/五子棋.html
markdown_extensions:
    - pymdownx.arithmatex

extra:
    history_buttons: false
